im0rtality_cold_breeze.rest.index:
    path:  /{resource}
    defaults:
        _controller: Im0rtalityColdBreezeBundle:Rest:list
        _format: json
    methods: [GET]
    requirements:
        resource: (orders|users|products)

im0rtality_cold_breeze.rest.get:
    path:  /{resource}/{id}
    defaults:
        _controller: Im0rtalityColdBreezeBundle:Rest:get
        _format: json
    methods: [GET]
    requirements:
        resource: (orders|users|products)

im0rtality_cold_breeze.rest.settings:
    path:  /settings
    defaults:
        _controller: Im0rtalityColdBreezeBundle:Rest:settings
        _format: json
    methods: [GET]

im0rtality_cold_breeze.rest.version:
    path:  /version
    defaults:
        _controller: Im0rtalityColdBreezeBundle:Rest:version
        _format: json
    methods: [GET]
