parameters:
    im0rtality_cold_breeze.serializer.class: Im0rtality\ColdBreezeBundle\Serializer
    im0rtality_cold_breeze.listener.exception.class: Im0rtality\ColdBreezeBundle\ExceptionListener
    im0rtality_cold_breeze.resource_repository.mapping:
        orders: order
        users: user
        products: product

    im0rtality_cold_breeze.resources_fields.mapping:
        Order:
            fields:
                - id
                - user
                - shippingAddress
                - billingAddress
                - currency
                - paymentState
                - shippingState
                - number
                - total
                - state
                - createdAt
                - updatedAt
                - completedAt
            expand:
                - shippingAddress
                - billingAddress
        User:
            fields:
                - id
                - firstName
                - lastName
                - email
                - orders
                - deleted
                - locked
                - lastLogin
            expand: []
        Address:
            fields:
                - firstName
                - lastName
                - company
                - country
                - street
                - city
                - postcode
            expand:
                - country
        Country:
            fields:
                - name
            expand: []
        Product:
            fields:
                - id
                - sku
                - name
                - shortDescription
                - images
                - masterVariant
                - variants
            expand:
                - images
                - variants
                - masterVariant
        ProductVariantImage:
            fields:
                - path
            expand: []
        ProductVariant:
            fields:
                - id
                - price
                - onHold
                - onHand
                - availableOnDemand
                - availableOn
                - available
                - options
            expand:
                - options
        OptionValue:
            fields:
                - value
                - name
            expand: []

services:
    im0rtality_cold_breeze.listener.exception:
        class: %im0rtality_cold_breeze.listener.exception.class%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }
        calls:
            - [setDebug, [%kernel.debug%]]

    im0rtality_cold_breeze.serializer:
        class: %im0rtality_cold_breeze.serializer.class%
        calls:
            - [setMapping, [%im0rtality_cold_breeze.resources_fields.mapping%]]

    im0rtality_cold_breeze.helper.settings:
        class: Im0rtality\ColdBreezeBundle\Helper\Settings
        calls:
            - [setImagineFilters, [%liip_imagine.filter_sets%]]
            - [setImagineCacheManager, [@liip_imagine.cache.manager]]
            - [setSettingsManager, [@sylius.settings.manager]]

    im0rtality_cold_breeze.helper.statistics:
        class: Im0rtality\ColdBreezeBundle\Helper\Statistics
        calls:
            - [setOrderRepository, [@sylius.repository.order]]
            - [setUserRepository, [@sylius.repository.user]]

    im0rtality_cold_breeze.helper.version:
        class: Im0rtality\ColdBreezeBundle\Helper\Version

    im0rtality_cold_breeze.user_provider:
        class:     Im0rtality\ColdBreezeBundle\Security\UserProvider
        arguments:
            - @fos_user.user_manager
            - []
        calls:
            - [setEntityManager, [@doctrine.orm.default_entity_manager]]

    im0rtality_cold_breeze.authenticator:
        class:     Im0rtality\ColdBreezeBundle\Security\Authenticator
        arguments:
            - @im0rtality_cold_breeze.user_provider
            - @security.http_utils

    im0rtality_cold_breeze.token_manager:
        class:     Im0rtality\ColdBreezeBundle\Security\TokenManager
        calls:
            - [setEntityManager, [@doctrine.orm.default_entity_manager]]

