parameters:
    im0rtality_cold_breeze.serializer.class: Im0rtality\ColdBreezeBundle\Serializer
    im0rtality_cold_breeze.listener.exception.class: Im0rtality\ColdBreezeBundle\ExceptionListener
    im0rtality_cold_breeze.resource_repository.mapping:
        orders: order
        users: user
        products: product

    im0rtality_cold_breeze.resources_fields.mapping:
        Order:
            fields:
                - id
                - user
                - shippingAddress
                - billingAddress
                - currency
                - paymentState
                - shippingState
                - number
                - total
                - state
                - createdAt
                - updatedAt
                - completedAt
            expand:
                - shippingAddress
                - billingAddress
        User:
            fields:
                - id
                - firstName
                - lastName
                - username
                - email
                - orders
            expand: []
        Address:
            fields:
                - firstName
                - lastName
                - company
                - country
                - province
                - street
                - city
                - postcode
                - createdAt
                - updatedAt
            expand: []
        Product:
            fields:
                - id
                - slug
                - name
                - shortDescription
                - images
            expand:
                - images
        ProductVariantImage:
            fields:
                - path
            expand: []

services:
    im0rtality_cold_breeze.listener.exception:
        class: %im0rtality_cold_breeze.listener.exception.class%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }
        calls:
            - [setDebug, [%kernel.debug%]]

    im0rtality_cold_breeze.serializer:
        class: %im0rtality_cold_breeze.serializer.class%
        calls:
            - [setMapping, [%im0rtality_cold_breeze.resources_fields.mapping%]]
